Repository LiskHQ/lisk-mobile, pull requests merged in 2018-11, with the labels that each got.

#314 Notifications controllers in settings - Closes #298
  src/assets/fonts/icons/icomoon.ttf
  src/assets/fonts/icons/selection.json
  src/components/ownWallet/index.js
  src/components/settings/index.js
  src/components/settings/itemTitle.js
  src/store/middlewares/socket.js
  src/store/middlewares/socket.test.js
  src/utilities/notifications.js
  src/utilities/storage.js
Labels: pending review

#316 Fix minor bugs and UX issues - Closes #315
  android/app/src/main/assets/fonts/icomoon.ttf
  package.json
  src/assets/fonts/icons/icomoon.ttf
  src/assets/fonts/icons/selection.json
  src/components/avatar/index.js
  src/components/login/index.js
  src/components/send/form/index.js
  src/components/send/form/styles.js
  src/components/settings/index.js
Labels: pending review

#330 Replace Login/Logout keywords with Sign In/Sign Out - Closes #277
  src/actions/accounts.js
  src/actions/accounts.test.js
  src/actions/peers.js
  src/components/intro/index.js
  src/components/landing/index.js
  src/components/ownWallet/index.js
  src/components/register/success/index.js
  src/components/request/index.js
  src/components/router/index.js
  src/components/send/confirm/index.js
  src/components/settings/index.js
  src/components/signIn/biometricAuth.js
  src/components/signIn/form.js
  src/components/signIn/index.js
  src/components/signIn/splash.js
  src/components/signIn/styles.js
  src/components/signOutButton/index.js
  src/components/signOutButton/styles.js
  src/components/transactions/index.js
  src/components/wallet/index.js
  src/constants/actions.js
  src/store/middlewares/socket.js
  src/store/middlewares/socket.test.js
  src/store/reducers/accounts.js
  src/store/reducers/accounts.test.js
  src/store/reducers/transactions.js
  src/store/reducers/transactions.test.js
  src/utilities/passphrase.js
Labels: ready

#334 Do not show keyboard when there is no input in the view - Closes #311
  android/app/src/main/AndroidManifest.xml
Labels: pending review

#337 Add usage of env.json to readme - Closes #333
  README.md
Labels: pending review

#341 Fix visual bugs in Login page - Closes #340
  src/components/login/biometricAuth.js
  src/components/login/form.js
  src/components/login/index.js
  src/components/login/splash.js
  src/components/send/form/index.js
Labels: pending review

#339 Update color constants for themes - Closes #338
  .gitignore
  src/components/about/styles.js
  src/components/accountSummary/styles.js
  src/components/copyToClipboard/index.js
  src/components/disableBioAuth/styles.js
  src/components/enableBioAuth/index.js
  src/components/enableBioAuth/styles.js
  src/components/fingerprintOverlay/index.js
  src/components/fingerprintOverlay/styles.js
  src/components/intro/heading.js
  src/components/intro/splash.js
  src/components/intro/styles.js
  src/components/loading/styles.js
  src/components/logo/index.js
  src/components/ownWallet/styles.js
  src/components/passphraseBackup/styles.js
  src/components/register/confirm/styles.js
  src/components/register/index.js
  src/components/register/intro/index.js
  src/components/register/intro/styles.js
  src/components/register/safeKeeping/styles.js
  src/components/register/styles.js
  src/components/register/success/styles.js
  src/components/request/index.js
  src/components/request/styles.js
  src/components/router/index.js
  src/components/router/logo.js
  src/components/router/menuIcon.js
  src/components/router/tabBarOptions.js
  src/components/search/styles.js
  src/components/send/confirm/styles.js
  src/components/send/form/cameraOverlay.js
  src/components/send/form/index.js
  src/components/send/form/styles.js
  src/components/send/index.js
  src/components/send/overview/styles.js
  src/components/send/result/styles.js
  src/components/settings/index.js
  src/components/settings/itemTitle.js
  src/components/settings/styles.js
  src/components/share/index.js
  src/components/signIn/biometricAuth.js
  src/components/signIn/splash.js
  src/components/signIn/styles.js
  src/components/signOutButton/index.js
  src/components/signOutButton/styles.js
  src/components/terms/styles.js
  src/components/toolBox/button.js
  src/components/toolBox/styles.js
  src/components/transactions/index.js
  src/components/transactions/styles.js
  src/components/txDetail/styles.js
  src/constants/styleGuide/colors.js
  yarn.lock
Labels: pending review

#349 Fix minor visual issues in the intro screen - Closes #347
  android/app/src/main/AndroidManifest.xml
  src/components/headerBackground/index.js
  src/components/headerBackground/styles.js
  src/components/intro/heading.js
  src/components/intro/styles.js
  src/components/login/splash.js
  src/components/login/styles.js
  src/components/router/index.js
Labels: pending review

#353 Bump version number 0.5.0 - Closes #352
  android/app/build.gradle
  android/app/src/main/java/io/lisk/mobile/MainApplication.java
  android/settings.gradle
  ios/Lisk.xcodeproj/project.pbxproj
  ios/Lisk/AppDelegate.m
  ios/Lisk/Info.plist
  package.json
  src/components/headerBackground/index.js
  src/components/headerBackground/styles.js
  src/components/intro/heading.js
  src/components/intro/index.js
  src/components/intro/styles.js
  src/components/landing/index.js
  src/components/ownWallet/index.js
  src/components/register/success/index.js
  src/components/router/index.js
  src/components/send/form/index.js
  src/components/settings/index.js
  src/components/signIn/biometricAuth.js
  src/components/signIn/form.js
  src/components/signIn/index.js
  src/components/signIn/splash.js
  src/components/signIn/styles.js
  src/store/middlewares/socket.js
  src/store/middlewares/socket.test.js
  src/utilities/notifications.js
Labels: pending review

#342 Implement dark mode to About and Terms screens - Closes #318
  src/components/about/index.js
  src/components/about/styles.js
  src/components/terms/index.js
  src/components/terms/styles.js
Labels: pending review

#346 Implement dark mode to PassphraseBackup and BioAuth screens - Closes #319
  src/assets/fonts/icons/icomoon.ttf
  src/assets/fonts/icons/selection.json
  src/assets/images/registrationProcess/passphrase-dark2x.png
  src/assets/images/registrationProcess/passphrase-dark3x.png
  src/components/disableBioAuth/index.js
  src/components/disableBioAuth/styles.js
  src/components/enableBioAuth/index.js
  src/components/enableBioAuth/styles.js
  src/components/passphraseBackup/index.js
  src/components/passphraseBackup/styles.js
  src/components/passphraseCopy/index.js
  src/components/passphraseCopy/styles.js
  src/constants/styleGuide/colors.js
Labels: pending review

#344 Implement dark mode to Settings screen - Closes #320
  src/components/settings/index.js
  src/components/settings/itemTitle/index.js
  src/components/settings/itemTitle/styles.js
  src/components/settings/styles.js
  src/components/signOutButton/index.js
  src/components/signOutButton/styles.js
  src/constants/styleGuide/colors.js
Labels: pending review

#358 Splash screen bug - Closes #357
  android/app/build.gradle
  src/components/signIn/splash.js
  src/components/signIn/styles.js
Labels: pending review

#350 Implement dark mode to Request screen - Closes #321
  src/components/request/index.js
  src/components/request/styles.js
  src/components/search/index.js
  src/components/send/confirm/index.js
  src/components/send/form/index.js
  src/components/share/index.js
  src/components/signIn/form.js
  src/components/toolBox/input.js
  src/components/toolBox/input/index.js
  src/components/toolBox/input/styles.js
Labels: pending review

#359 Add controllers for dark mode in the settings page - Closes #324
  android/app/src/main/assets/fonts/icomoon.ttf
  ios/Lisk.xcodeproj/project.pbxproj
  src/App.js
  src/assets/fonts/icons/icomoon.ttf
  src/assets/fonts/icons/selection.json
  src/components/settings/index.js
  src/components/settings/itemTitle/index.js
  src/components/settings/itemTitle/styles.js
  src/components/settings/styles.js
  src/components/settings/switchButton.js
  src/store/reducers/settings.js
  src/store/reducers/settings.test.js
Labels: pending review

#351 Update validation flow of SignIn Form - Closes #304
  src/components/signIn/form.js
  src/components/signIn/index.js
Labels: pending review

#364 Add a controller for the incognito mode in the Settings and Home pages - Closes #325
  src/components/settings/index.js
  src/components/transactions/index.js
  src/components/transactions/styles.js
Labels: pending review

#355 Implement the dark mode of the transaction details page - Closes #327
  src/assets/images/txDetail/arrow-dark2x.png
  src/assets/images/txDetail/arrow-dark3x.png
  src/assets/images/txDetail/arrow-light2x.png
  src/components/txDetail/index.js
  src/components/txDetail/styles.js
Labels: pending review

#366 Update Share button props in Request screen - Closes #365
  src/components/request/index.js
Labels: pending review

#362 Implement the dark mode of the home - Closes #323
  src/assets/images/loading2x.png
  src/assets/images/loading3xDark.png
  src/assets/images/loading3xLight.png
  src/assets/images/noActivity/noActivity2x.png
  src/assets/images/noActivity/noActivity3xDark.png
  src/assets/images/noActivity/noActivity3xLight.png
  src/assets/images/stripesDark.png
  src/assets/images/stripesLight.png
  src/components/accountSummary/index.js
  src/components/accountSummary/styles.js
  src/components/enableBioAuth/index.js
  src/components/headerBackground/index.js
  src/components/ownWallet/index.js
  src/components/ownWallet/styles.js
  src/components/router/index.js
  src/components/router/menuIcon.js
  src/components/router/tabBarOptions.js
  src/components/transactions/empty.js
  src/components/transactions/index.js
  src/components/transactions/item.js
  src/components/transactions/loading.js
  src/components/transactions/styles.js
  src/constants/styleGuide/colors.js
Labels: pending review

#367 Use scrollToTop function passed from OwnWallet in router - Closes 193
  src/components/ownWallet/index.js
  src/components/passphraseCopy/index.js
  src/components/router/index.js
  src/components/signIn/biometricAuth.js
Labels: pending review

#370 Implement the dark mode of the send screen - Closes #322
  src/assets/images/camera2x.png
  src/assets/images/camera3xDark.png
  src/assets/images/camera3xLight.png
  src/assets/images/secondPassphrase2x.png
  src/assets/images/secondPassphrase3xDark.png
  src/assets/images/secondPassphrase3xLight.png
  src/components/send/confirm/index.js
  src/components/send/confirm/styles.js
  src/components/send/form/cameraAccess.js
  src/components/send/form/index.js
  src/components/send/form/styles.js
  src/components/send/overview/index.js
  src/components/send/overview/styles.js
  src/components/send/result/index.js
  src/components/send/result/styles.js
  src/components/signIn/form.js
  src/components/withTheme/index.js
  src/utilities/helpers.js
Labels: pending review

#354 Use deep link for request urls - Closes #328
  android/app/src/main/AndroidManifest.xml
  ios/Lisk/AppDelegate.m
  ios/Lisk/Info.plist
  package.json
  src/components/multiStep/index.js
  src/components/send/form/index.js
  src/components/send/index.js
  src/components/signIn/index.js
  src/utilities/deepLink.js
  src/utilities/deepLink.test.js
Labels: pending review

#384 Use current theme in InfiniteScrollView component
  src/components/infiniteScrollView/index.js
  src/components/ownWallet/index.js
Labels: pending review

#385 Implement the blur effect over the transaction and balance values - Closes #326
  src/assets/images/amountBlur/incoming/darkMedium.png
  src/assets/images/amountBlur/incoming/darkSmall.png
  src/assets/images/amountBlur/incoming/lightMedium.png
  src/assets/images/amountBlur/incoming/lightSmall.png
  src/assets/images/amountBlur/outgoing/darkMedium.png
  src/assets/images/amountBlur/outgoing/darkSmall.png
  src/assets/images/amountBlur/outgoing/lightMedium.png
  src/assets/images/amountBlur/outgoing/lightSmall.png
  src/assets/images/balanceBlur/darkBig.png
  src/assets/images/balanceBlur/darkMedium.png
  src/assets/images/balanceBlur/darkSmall.png
  src/assets/images/balanceBlur/lightBig.png
  src/assets/images/balanceBlur/lightMedium.png
  src/assets/images/balanceBlur/lightSmall.png
  src/components/accountSummary/index.js
  src/components/accountSummary/styles.js
  src/components/formattedNumber/index.js
  src/components/router/index.js
  src/components/send/form/index.js
  src/components/send/overview/index.js
  src/components/settings/index.js
  src/components/transactions/blur.js
  src/components/transactions/index.js
  src/components/transactions/item.js
  src/components/transactions/list.js
  src/components/transactions/styles.js
  src/components/txDetail/index.js
  src/components/txDetail/styles.js
Labels: pending review

#360 Use npm ci - Closes #356
  .gitignore
  .nvmrc
  Jenkinsfile
  package-lock.json
  package.json
Labels: pending review

#396 Implement the logic of bookmarks in our Redux store - Closes #374
  src/store/reducers/accounts.js
  src/store/reducers/accounts.test.js
Labels: ready

#394 Reset the BioAuth method after signing out - Closes #392
  src/components/signOutButton/index.js
Labels: ready

#398 Implement the Recipient step of the Send screen. - Closes #375
  src/assets/images/send/noBookmarks3xDark.png
  src/assets/images/send/noBookmarks3xLight.png
  src/components/bookmarks/empty.js
  src/components/bookmarks/index.js
  src/components/bookmarks/item.js
  src/components/bookmarks/styles.js
  src/components/send/form/index.js
  src/components/send/index.js
  src/components/send/recipient/cameraAccess.js
  src/components/send/recipient/cameraOverlay.js
  src/components/send/recipient/cameraRoll.js
  src/components/send/recipient/index.js
  src/components/send/recipient/scanner.js
  src/components/send/recipient/styles.js
  src/components/toolBox/keyboardAwareScrollView.js
  src/components/toolBox/styles.js
Labels: in progress

#391 Implement the Amount step of the Send page with exchange ratio logic - Closes #380
  src/components/formattedNumber/index.js
  src/components/send/amount/index.js
  src/components/send/amount/input/index.js
  src/components/send/amount/input/styles.js
  src/components/send/amount/styles.js
  src/components/send/index.js
  src/components/toolBox/input/index.js
  src/constants/styleGuide/colors.js
  src/utilities/api/liskService.js
  src/utilities/http.js
Labels: pending review

#400 Implement the Reference step of the Send screen - Closes #377
  src/components/send/amount/index.js
  src/components/send/index.js
  src/components/send/recipient/index.js
  src/components/send/reference/index.js
  src/components/send/reference/styles.js
Labels: pending review

#405 Implement the new design of the Overview page - Closes #378
  android/app/src/main/assets/fonts/icomoon.ttf
  src/assets/fonts/icons/icomoon.ttf
  src/assets/fonts/icons/selection.json
  src/components/send/overview/index.js
  src/components/send/overview/styles.js
Labels: pending review

#408 Refactor Register screen's navigation listeners - Closes #402
  src/components/register/index.js
  src/components/register/intro/index.js
  src/components/register/success/index.js
  src/components/settings/index.js
Labels: pending review

#406 Make QR code touchable on Request screen - Closes #404
  src/components/request/index.js
  src/components/request/styles.js
Labels: pending review

#412 Add to bookmarks step of the send component - Closes #376
  src/actions/accounts.js
  src/actions/accounts.test.js
  src/components/send/addToBookmark/index.js
  src/components/send/addToBookmark/styles.js
  src/components/send/amount/index.js
  src/components/send/index.js
  src/components/send/recipient/index.js
  src/components/send/reference/index.js
  src/components/toolBox/keyboardAwareScrollView.js
Labels: pending review

#387 Fix minor visual bugs - Closes #386
  android/app/build.gradle
  android/app/src/main/assets/fonts/icomoon.ttf
  ios/Lisk.xcodeproj/project.pbxproj
  ios/Lisk/Info.plist
  package.json
  src/assets/fonts/icons/icomoon.ttf
  src/assets/fonts/icons/selection.json
  src/assets/images/txDetail/accountInitialization2x.png
  src/assets/images/txDetail/accountInitialization3xDark.png
  src/assets/images/txDetail/accountInitialization3xLight.png
  src/assets/images/txDetail/arrow-dark3x.png
  src/assets/images/txDetail/registerDelegate2x.png
  src/assets/images/txDetail/registerDelegate3xDark.png
  src/assets/images/txDetail/registerDelegate3xLight.png
  src/assets/images/txDetail/setSecondPassphrase2x.png
  src/assets/images/txDetail/setSecondPassphrase3xDark.png
  src/assets/images/txDetail/setSecondPassphrase3xLight.png
  src/assets/images/txDetail/vote2x.png
  src/assets/images/txDetail/vote3xDark.png
  src/assets/images/txDetail/vote3xLight.png
  src/components/about/index.js
  src/components/accountSummary/index.js
  src/components/accountSummary/styles.js
  src/components/passphraseCopy/styles.js
  src/components/router/index.js
  src/components/scanner/cameraAccess.js
  src/components/scanner/cameraOverlay.js
  src/components/scanner/cameraRoll.js
  src/components/scanner/closureOverlay.js
  src/components/scanner/index.js
  src/components/scanner/styles.js
  src/components/settings/index.js
  src/components/settings/itemTitle/index.js
  src/components/settings/itemTitle/styles.js
  src/components/settings/styles.js
  src/components/share/index.js
  src/components/signIn/form.js
  src/components/signIn/styles.js
  src/components/transactions/index.js
  src/components/transactions/item.js
  src/components/transactions/list.js
  src/components/txDetail/index.js
  src/constants/transactions.js
Labels: pending review

#414 Use Node.js 8.13.0 - Closes #413
  .nvmrc
Labels: ready

#395 Add App Store and Play Store links to README
  README.md
Labels: pending review
