Repository LiskHQ/lisk-mobile, pull requests merged in 2018-12, with the labels that each got.

#427 Fix account initialization bugs on the send screen - Closes #425
  src/components/send/index.js
  src/components/send/overview/index.js
Labels: pending review

#411 Increase the unit test coverage of the utilities - Closes #410
  .eslintrc
  __mocks__/AsyncStorage.js
  package-lock.json
  package.json
  src/actions/accounts.test.js
  src/actions/settings.test.js
  src/store/middlewares/accounts.test.js
  src/store/middlewares/settings.js
  src/store/middlewares/settings.test.js
  src/store/middlewares/socket.js
  src/store/middlewares/socket.test.js
  src/utilities/api/account.js
  src/utilities/api/account.test.js
  src/utilities/api/liskService.test.js
  src/utilities/api/transactions.js
  src/utilities/api/transactions.test.js
  src/utilities/deepLink.test.js
  src/utilities/helpers.js
  src/utilities/helpers.test.js
  src/utilities/storage.js
  src/utilities/storage.test.js
Labels: pending review

#436 Fix styling of Settings screen for FingerprintOverlay - Closes #431
  src/components/settings/index.js
  src/components/settings/styles.js
Labels: pending review

#428 Fix visual issues in Send and Sign in screens - Closes #426
  src/components/send/amount/index.js
  src/components/send/overview/index.js
  src/components/send/overview/styles.js
  src/components/send/recipient/index.js
  src/components/send/reference/index.js
  src/components/send/reference/styles.js
  src/components/signIn/splash.js
  src/components/signIn/styles.js
Labels: pending review

#443 Refactor navigation elements for new design - Closes #441, #439
  src/components/accountSummary/styles.js
  src/components/headerBackground/index.js
  src/components/router/headerBackButton/index.js
  src/components/router/headerBackButton/styles.js
  src/components/router/headerBackground/index.js
  src/components/router/headerBackground/styles.js
  src/components/router/headerBackgroundImage/index.js
  src/components/router/headerBackgroundImage/styles.js
  src/components/router/headerLogo/index.js
  src/components/router/headerPlaceholderButton/index.js
  src/components/router/headerTitle/index.js
  src/components/router/headerTitle/styles.js
  src/components/router/index.js
  src/components/router/logo.js
  src/components/router/menuIcon.js
  src/components/router/styles.js
  src/components/router/tabBarComponent/index.js
  src/components/router/tabBarComponent/styles.js
  src/components/router/tabBarIcon/index.js
  src/components/router/tabBarOptions.js
  src/components/txDetail/styles.js
  src/constants/styleGuide/colors.js
Labels: pending review

#447 Refactor screen titles for new design
  src/App.js
  src/components/about/index.js
  src/components/about/styles.js
  src/components/currencySelection/index.js
  src/components/currencySelection/styles.js
  src/components/disableBioAuth/index.js
  src/components/disableBioAuth/styles.js
  src/components/enableBioAuth/index.js
  src/components/enableBioAuth/styles.js
  src/components/passphraseBackup/index.js
  src/components/passphraseBackup/styles.js
  src/components/request/index.js
  src/components/request/styles.js
  src/components/router/index.js
  src/components/send/addToBookmark/index.js
  src/components/send/addToBookmark/styles.js
  src/components/send/amount/index.js
  src/components/send/amount/styles.js
  src/components/send/confirm/index.js
  src/components/send/confirm/styles.js
  src/components/send/index.js
  src/components/send/overview/index.js
  src/components/send/overview/styles.js
  src/components/send/recipient/index.js
  src/components/send/recipient/styles.js
  src/components/send/reference/index.js
  src/components/send/reference/styles.js
  src/components/send/result/index.js
  src/components/send/result/styles.js
  src/components/settings/index.js
  src/components/settings/styles.js
  src/components/txDetail/index.js
  src/components/txDetail/styles.js
Labels: pending review

#453 Use haptic feedback for changes triggered via switch or toggle - Closes #415
  android/app/build.gradle
  android/app/src/main/java/io/lisk/mobile/MainApplication.java
  android/settings.gradle
  ios/Lisk.xcodeproj/project.pbxproj
  ios/Lisk/Info.plist
  package-lock.json
  package.json
  src/components/settings/switchButton.js
  src/components/transactions/index.js
Labels: pending review

#442 Hide balance on Amount step for discreet mode - Closes #418
  src/assets/images/amountFormBalanceBlur/dark.png
  src/assets/images/amountFormBalanceBlur/light.png
  src/components/send/amount/index.js
  src/components/send/amount/styles.js
  src/components/send/index.js
Labels: pending review

#452 Add warning before sign out - Closes #424
  src/components/settings/index.js
  src/components/settings/signOutButton/index.js
  src/components/settings/signOutButton/styles.js
Labels: pending review

#450 Create liskService module - Closes #445
  src/actions/liskService.js
  src/actions/liskService.test.js
  src/components/send/amount/index.js
  src/components/signIn/index.js
  src/constants/actions.js
  src/store/reducers/index.js
  src/store/reducers/liskService.js
  src/store/reducers/liskService.test.js
Labels: pending review

#451 Implement the Christmas look on the SignIn screen - Closes #438
  src/assets/images/christmasHat.png
  src/components/signIn/splash.js
  src/components/signIn/styles.js
Labels: pending review

#446 Implement the new design of the home page - Closes #434
  src/assets/images/bg.png
  src/components/accountSummary/index.js
  src/components/accountSummary/styles.js
  src/components/home/index.js
  src/components/home/styles.js
  src/components/infiniteScrollView/index.js
  src/components/register/confirm/styles.js
  src/components/router/headerBackButton/styles.js
  src/components/router/headerBackgroundImage/index.js
  src/components/router/headerBackgroundImage/styles.js
  src/components/router/headerTitle/styles.js
  src/components/router/homeHeaderTitle/index.js
  src/components/router/homeHeaderTitle/styles.js
  src/components/router/index.js
  src/components/router/tabBarIcon/index.js
  src/components/send/index.js
  src/components/signIn/index.js
  src/components/transactions/index.js
  src/components/transactions/styles.js
Labels: pending review

#448 Implement the bookmark page - Closes #432
  android/app/build.gradle
  android/app/src/main/assets/fonts/icomoon.ttf
  android/app/src/main/java/io/lisk/mobile/MainApplication.java
  android/settings.gradle
  ios/Lisk.xcodeproj/project.pbxproj
  package-lock.json
  package.json
  src/assets/fonts/icons/icomoon.ttf
  src/assets/fonts/icons/selection.json
  src/components/bookmarkPage/addButton.js
  src/components/bookmarkPage/index.js
  src/components/bookmarkPage/styles.js
  src/components/bookmarks/index.js
  src/components/bookmarks/item.js
  src/components/bookmarks/styles.js
  src/components/router/index.js
Labels: pending review

#465 Implement add to bookmark page - Closes #458
  src/actions/accounts.js
  src/actions/accounts.test.js
  src/components/addBookmark/index.js
  src/components/addBookmark/styles.js
  src/components/bookmarkPage/index.js
  src/components/bookmarkPage/styles.js
  src/components/bookmarks/item.js
  src/components/router/headerBackButton/index.js
  src/components/router/index.js
  src/components/send/addToBookmark/index.js
  src/utilities/storage.js
  src/utilities/storage.test.js
Labels: pending review

#449 Refactor validation flow of inputs - Closes #423
  src/components/send/amount/index.js
  src/components/send/confirm/index.js
  src/components/send/confirm/styles.js
  src/components/send/reference/index.js
  src/components/signIn/form.js
  src/components/signIn/index.js
  src/components/signIn/styles.js
  src/utilities/passphrase.js
Labels: pending review

#464 Show step progress on Send screen
  src/actions/transactions.js
  src/actions/transactions.test.js
  src/components/multiStep/index.js
  src/components/send/addToBookmark/index.js
  src/components/send/amount/index.js
  src/components/send/confirm/index.js
  src/components/send/index.js
  src/components/send/overview/index.js
  src/components/send/progress.js
  src/components/send/recipient/index.js
  src/components/send/reference/index.js
  src/components/send/result/index.js
  src/components/send/styles.js
Labels: pending review

#461 Fix minor visual bugs - Closes #460
  package-lock.json
  src/actions/accounts.js
  src/actions/accounts.test.js
  src/actions/transactions.js
  src/actions/transactions.test.js
  src/components/accountSummary/index.js
  src/components/home/index.js
  src/components/infiniteScrollView/index.js
  src/components/request/index.js
  src/components/request/styles.js
  src/components/send/amount/styles.js
  src/components/send/index.js
  src/components/send/overview/index.js
  src/components/send/overview/styles.js
  src/components/send/result/index.js
  src/components/signIn/splash.js
  src/components/transactions/empty.js
  src/components/transactions/index.js
  src/components/transactions/styles.js
  src/store/reducers/transactions.js
  src/store/reducers/transactions.test.js
Labels: pending review

#466 Implement the wallet page for other accounts - Closes #435
  android/app/src/main/assets/fonts/icomoon.ttf
  src/assets/fonts/icons/icomoon.ttf
  src/assets/fonts/icons/selection.json
  src/components/accountSummary/index.js
  src/components/accountSummary/styles.js
  src/components/home/index.js
  src/components/router/homeHeaderTitle/index.js
  src/components/router/homeHeaderTitle/styles.js
  src/components/router/index.js
  src/components/transactions/index.js
  src/components/transactions/styles.js
  src/components/txDetail/index.js
  src/components/txDetail/styles.js
  src/components/wallet/index.js
  src/components/wallet/styles.js
Labels: pending review

#459 Link the addresses to the Wallet page - Closes #433
  src/components/txDetail/index.js
Labels: pending review

#476 Link bookmark items to wallet page - Closes #475
  src/components/accountSummary/index.js
  src/components/addBookmark/index.js
  src/components/bookmarks/item.js
Labels: pending review

#482 Show less floating digits when the number is big - Closes #416
  package-lock.json
  package.json
  src/components/formattedNumber/index.js
  src/components/transactions/item.js
Labels: pending review

#484 Update bookmark item to ask for confirmation before delete - Closes #480
  src/components/accountSummary/index.js
  src/components/bookmarks/item.js
Labels: pending review

#472 Refactor QR code scanner component, Closes #278
  src/components/addBookmark/index.js
  src/components/addBookmark/styles.js
  src/components/scanner/cameraRoll.js
  src/components/scanner/closureOverlay.js
  src/components/scanner/index.js
  src/components/send/recipient/cameraAccess.js
  src/components/send/recipient/cameraOverlay.js
  src/components/send/recipient/cameraRoll.js
  src/components/send/recipient/index.js
  src/components/send/recipient/scanner.js
  src/components/send/recipient/styles.js
  src/components/signIn/form.js
  src/components/signIn/styles.js
  src/utilities/qrCode.js
  src/utilities/qrCode.test.js
Labels: pending review

#487 Your account must not be linked in transaction details page - Closes #478
  src/components/txDetail/index.js
Labels: pending review

#490 Fix some minor visual bugs - Closes #489
  src/components/accountSummary/index.js
  src/components/accountSummary/styles.js
  src/components/bookmarkPage/index.js
  src/components/transactions/styles.js
Labels: pending review

#494 Fix some bugs in the addToBookmark page - Closes #493
  src/components/addBookmark/index.js
Labels: pending review

#481 The header of TxDetail navigated from Wallet should be light - Closes #479
  src/components/router/index.js
  src/components/txDetail/styles.js
Labels: pending review

#492 Fix minor visual bugs on Home and Wallet screens
  src/components/accountSummary/index.js
  src/components/home/index.js
  src/components/router/homeHeaderTitle/index.js
  src/components/router/homeHeaderTitle/styles.js
  src/components/transactions/index.js
  src/components/wallet/index.js
Labels: in progress

#488 Error messages inaccuracy in Send screen - Closes #486
  src/components/addBookmark/index.js
  src/components/bookmarks/index.js
  src/components/send/amount/index.js
  src/components/send/recipient/index.js
Labels: pending review

#501 Status bar color on ios - Closes #500
  src/components/home/index.js
  src/components/router/homeHeaderTitle/index.js
Labels: pending review

#499 Fix reference value overflow on TxDetails Screen - Closes #495
  src/components/txDetail/index.js
  src/components/txDetail/styles.js
Labels: pending review

#505 Fix exchange rate visibility condition - Closes #504
  src/components/send/amount/index.js
Labels: pending review

#498 Fix the alignment of Address and bookmark label on Ready to Send step - Closes #496
  src/components/send/overview/index.js
  src/components/send/overview/styles.js
Labels: ready

#506 Fix misalignments in the bookmarks and Send page - Closes #503
  android/app/src/main/assets/fonts/icomoon.ttf
  src/assets/fonts/icons/icomoon.ttf
  src/assets/fonts/icons/selection.json
  src/components/bookmarkPage/index.js
  src/components/bookmarkPage/styles.js
  src/components/bookmarks/index.js
  src/components/send/recipient/index.js
  src/components/send/recipient/styles.js
Labels: pending review

#508 Bump version number 0.8.0 - Closes #507
  android/app/build.gradle
  ios/Lisk/Info.plist
  package-lock.json
  package.json
Labels: pending review

#512 Fix the regex in FormattedNumber - Closes #511
  src/components/formattedNumber/index.js
Labels: pending review

#510 Add validation for empty submission case in Recipient and Amount steps
  src/components/send/amount/index.js
  src/components/send/recipient/index.js
Labels: pending review

#514 Simplify copy on Bookmarks Page
  ios/Lisk.xcodeproj/project.pbxproj
  ios/Lisk/Info.plist
  src/components/bookmarkPage/index.js
  src/components/send/addToBookmark/index.js
Labels: pending review

#517 Fix issues with formatting the transactions amount - Closes #516
  src/components/accountSummary/index.js
  src/components/addBookmark/styles.js
  src/components/formattedNumber/index.js
  src/components/send/amount/input/index.js
  src/components/send/overview/styles.js
  src/components/transactions/item.js
  src/utilities/conversions.js
Labels: pending review

#525 Fix broken release android script - Closes #521
  android/build.gradle
  android/gradle.properties
Labels: pending review

#522 Fix styling of navigation elements - Closes #520
  src/components/router/index.js
  src/components/router/tabBarComponent/styles.js
Labels: pending review

#519 Fix alignment of the copyright text in About page - Closes #518
  ios/Lisk/Info.plist
  src/components/about/styles.js
Labels: pending review

#524 Add back button to the scanner camera access overlay - Closes #523
  src/components/scanner/cameraAccess.js
  src/components/scanner/index.js
  src/components/scanner/styles.js
  src/components/signIn/form.js
Labels: pending review

#527 Add rounded icon to the android configuration - Closes #526
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
Labels: pending review

#528 Bump iOS build number
  ios/Lisk/Info.plist
Labels: pending review

#437 Show embeddable build status icons in README - Closes #417
  Jenkinsfile
  README.md
  jest.config.js
  jest/eslint-config.js
  jest/main-config.js
  jest/test-config.js
  package-lock.json
  package.json
Labels: pending review
