Repository LiskHQ/lisk-mobile, pull requests merged in 2019-07, with the labels that each got.

#895 Translate recently added titles - Closes #894
  locales/resources/de.json
  locales/resources/en.json
  src/components/signIn/biometricAuth/index.js
Labels: pending review

#899 The add bookmark button is invisible in bookmarks page - Closes #898
  src/components/bookmarkPage/index.js
Labels: pending review

#889 Bump version 1.2.0 - Closes #867
  android/app/build.gradle
  ios/Lisk.xcodeproj/project.pbxproj
  ios/Lisk/Images.xcassets/AppIcon.appiconset/1024x1024.png
  ios/Lisk/Info.plist
  ios/LiskMessageExtension/Info.plist
  package.json
Labels: pending review

#841 Add e2e to jenkins - Closes #837
  Jenkinsfile
  e2e/features/1_intro.feature
  e2e/features/registration.feature
  e2e/features/signin.feature
  e2e/features/step_definitions/common.js
  e2e/features/step_definitions/profile.js
  e2e/features/step_definitions/registration.js
  e2e/features/step_definitions/signin.js
  e2e/features/support/hooks.js
  ios/Lisk.xcodeproj/project.pbxproj
  jest.config.js
  package.json
  src/components/intro/heading.js
  src/components/intro/index.js
  src/components/register/intro/index.js
  src/components/register/safeKeeping/index.js
  src/components/register/success/index.js
Labels: Mobile, in progress

#902 Update to React Native 0.59 - Closes #835
  .babelrc
  README.md
  android/app/BUCK
  android/app/build.gradle
  android/app/build_defs.bzl
  android/app/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/io/lisk/mobile/MainApplication.java
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
  babel.config.js
  ios/Lisk.xcodeproj/project.pbxproj
  ios/Lisk/AppDelegate.h
  ios/Lisk/AppDelegate.m
  ios/Lisk/main.m
  jest.config.js
  metro.config.js
  package-lock.json
  package.json
  src/utilities/storage.js
  src/utilities/storage.test.js
Labels: pending review

#907 Fix alignment of transaction item - Closes #906
  src/components/transactions/styles.js
Labels: ready

#904 App crashes after removing BTC - Closes #903
  src/components/home/index.js
Labels: ready

#915 App crashes after adding BTC in Settings - Closes #913
  src/actions/accounts.js
  src/components/home/index.js
Labels: pending review

#909 You can't run the app in discreet mode if it's already run - Closes #887
  src/components/screens/signIn/index.js
  src/components/screens/tabs/home/index.js
Labels: pending review

#900 Add SafeAreaView to components - Closes #822
  android/app/build.gradle
  android/app/src/main/java/io/lisk/mobile/MainApplication.java
  android/settings.gradle
  ios/Lisk.xcodeproj/project.pbxproj
  jest.config.js
  package-lock.json
  package.json
  src/components/screens/disableBioAuth/index.js
  src/components/screens/disableBioAuth/styles.js
  src/components/screens/enableBioAuth/index.js
  src/components/screens/enableBioAuth/styles.js
  src/components/screens/intro/index.js
  src/components/screens/intro/styles.js
  src/components/screens/passphraseBackup/index.js
  src/components/screens/passphraseBackup/styles.js
  src/components/screens/register/confirm/index.js
  src/components/screens/register/confirm/styles.js
  src/components/screens/register/intro/index.js
  src/components/screens/register/intro/styles.js
  src/components/screens/register/safeKeeping/index.js
  src/components/screens/register/safeKeeping/styles.js
  src/components/screens/register/styles.js
  src/components/screens/register/success/index.js
  src/components/screens/register/success/styles.js
  src/components/screens/router/tabBarComponent/index.js
  src/components/shared/loading/styles.js
  src/components/shared/modal/styles.js
  src/components/shared/toolBox/styles.js
  src/utilities/device.js
  testenv.js
Labels: ready
