Repository LiskHQ/lisk-mobile, pull requests merged in 2019-05, with the labels that each got.

#789 Migrate remaining parts of SignIn to new design - Closes #787
  src/assets/images/christmasHat.png
  src/assets/images/topBubbles2x.png
  src/assets/images/topBubbles3x.png
  src/components/signIn/biometricAuth/index.js
  src/components/signIn/biometricAuth/styles.js
  src/components/signIn/form/index.js
  src/components/signIn/form/styles.js
  src/components/signIn/index.js
  src/components/signIn/splash.js
  src/components/signIn/splash/index.js
  src/components/signIn/splash/styles.js
  src/components/signIn/styles.js
  src/components/signIn/title/index.js
  src/components/signIn/title/styles.js
Labels: pending review

#804 Improve general modal component performance on android - Closes #803
  ios/Lisk.xcodeproj/project.pbxproj
  package-lock.json
  package.json
  src/App.js
  src/components/assetSelection/index.js
  src/components/modal/index.js
  src/components/modal/styles.js
  src/components/router/index.js
  src/components/router/tokenSwitcher/index.js
  src/utilities/modal.js
Labels: pending review

#802 Migrate Summary step of Send to the new design - Closes #763
  locales/resources/de.json
  locales/resources/en.json
  src/components/send/overview/index.js
  src/components/send/overview/styles.js
  src/components/txDetail/index.js
Labels: pending review

#799 Migrate Amount step of Send to the new design - Closes #760
  locales/resources/de.json
  locales/resources/en.json
  src/components/send/amount/balance/index.js
  src/components/send/amount/balance/styles.js
  src/components/send/amount/btc.js
  src/components/send/amount/dynamicFeeSelector/index.js
  src/components/send/amount/dynamicFeeSelector/styles.js
  src/components/send/amount/header/index.js
  src/components/send/amount/header/styles.js
  src/components/send/amount/input/index.js
  src/components/send/amount/input/styles.js
  src/components/send/amount/lsk.js
Labels: ready

#800 Migrate Success step of Send to the new design - Closes #764
  locales/resources/de.json
  locales/resources/en.json
  src/actions/transactions.js
  src/components/send/addToBookmark/index.js
  src/components/send/addToBookmark/styles.js
  src/components/send/amount/index.js
  src/components/send/index.js
  src/components/send/recipient/index.js
  src/components/send/result/index.js
  src/components/send/result/styles.js
Labels: ready

#738 Use new modal to confirm Sign Out action - Closes #735
  locales/resources/de.json
  locales/resources/en.json
  src/components/modal/index.js
  src/components/settings/index.js
  src/components/settings/signOutButton/index.js
  src/components/settings/signOutModal/index.js
  src/components/settings/signOutModal/styles.js
  src/utilities/modal.test.js
Labels: pending review

#808 Fix missing reference in Lisk transactions - Resolves #807
  src/actions/transactions.js
  src/utilities/api/lisk/transactions.js
Labels: pending review

#806 Fix the issue with the home page title
  src/components/home/index.js
Labels: pending review

#745 Use new modal to confirm the bookmark removal - Closes #736
  locales/resources/de.json
  locales/resources/en.json
  src/components/accountSummary/wallet.js
  src/components/bookmarks/deleteBookmarkModal/index.js
  src/components/bookmarks/deleteBookmarkModal/styles.js
  src/components/bookmarks/item.js
Labels: pending review

#811 Add BTC introduction modal - Closes #798
  locales/resources/de.json
  locales/resources/en.json
  src/components/home/index.js
  src/components/home/introModal/index.js
  src/components/home/introModal/styles.js
  src/components/modal/index.js
Labels: pending review

#813 Translate the new titles - Closes #812
  locales/resources/de.json
  locales/resources/en.json
  src/components/addBookmark/index.js
  src/components/bookmarkPage/index.js
  src/components/fingerprintOverlay/index.js
  src/components/imessage/form/index.js
  src/components/register/success/index.js
  src/components/send/result/index.js
  src/components/transactions/index.js
Labels: pending review

#816 Fix typos in the bookmarks page - Closes #815
  locales/resources/de.json
  locales/resources/en.json
  src/components/bookmarks/empty.js
Labels: pending review

#805 Migrate Address step of Send to the new design - Closes #759
  locales/resources/de.json
  locales/resources/en.json
  src/assets/images/send/noBookmarks3xDark.png
  src/assets/images/send/noBookmarks3xLight.png
  src/components/bookmarks/empty.js
  src/components/bookmarks/styles.js
  src/components/send/progress.js
  src/components/send/recipient/index.js
  src/components/send/recipient/styles.js
  src/components/send/styles.js
Labels: pending review

#819 Fix the bookmarks look up logic - Closes #817
  locales/resources/de.json
  locales/resources/en.json
  src/components/bookmarkPage/index.js
  src/components/bookmarks/index.js
  src/components/home/index.js
Labels: pending review

#818 Migrate transaction details to the new design - Closes #756
  src/assets/images/txDetail/arrow-dark2x.png
  src/assets/images/txDetail/arrow-light2x.png
  src/components/txDetail/btcSummary.js
  src/components/txDetail/index.js
  src/components/txDetail/lskSummary.js
  src/components/txDetail/row.js
  src/components/txDetail/styles.js
Labels: in progress

#809 Migrate Passphrase step of Registration to the new design - Closes #767
  locales/resources/de.json
  locales/resources/en.json
  src/assets/images/send/secondPassphrase3xDark.png
  src/assets/images/send/secondPassphrase3xLight.png
  src/components/send/secondPassphrase/index.js
  src/components/send/secondPassphrase/styles.js
Labels: pending review

#795 Bump version 1.1.0 - Closes #793
  ios/Lisk.xcodeproj/xcshareddata/xcschemes/Lisk.xcscheme
  ios/Lisk/Info.plist
  ios/LiskMessageExtension/Info.plist
Labels: pending review

#801 Migrate Message step of Send to the new design - Closes #762
  locales/resources/de.json
  locales/resources/en.json
  src/components/send/recipient/index.js
  src/components/send/reference/circularProgress.js
  src/components/send/reference/index.js
  src/components/send/reference/styles.js
Labels: pending review

#826 Fix the iMessage extension rendering issue - Closes #824
  ios/LiskMessageExtension/MessagesManager.m
  src/components/wallet/index.js
Labels: pending review

#825 Fixed an issue with infinite scroll in wallet page - Closes #823
  src/components/wallet/index.js
Labels: pending review

#814 Migrate Request to the new design - Closes #757
  locales/resources/en.json
  src/components/request/index.js
  src/components/request/styles.js
Labels: pending review

#810 Initial detox setup - Closes #467
  .eslintrc
  e2e/features/registration.feature
  e2e/features/signin.feature
  e2e/features/step_definitions/common.js
  e2e/features/step_definitions/profile.js
  e2e/features/step_definitions/registration.js
  e2e/features/support/hooks.js
  e2e/features/support/timeouts.js
  jest.config.js
  package-lock.json
  package.json
  src/components/accountSummary/profile.js
  src/components/intro/heading.js
  src/components/register/confirm/index.js
  src/components/register/initialization/index.js
  src/components/register/intro/index.js
  src/components/register/safeKeeping/index.js
  src/components/register/success/index.js
  src/components/signIn/createAccount/index.js
  src/components/signIn/form/index.js
  src/components/signIn/index.js
  src/components/toolBox/button/index.js
  src/components/toolBox/input/index.js
  src/components/toolBox/keyboardAwareScrollView.js
  src/components/toolBox/typography.js
  src/utilities/deepLink.js
Labels: pending review

#834 Bump version 1.1.0 - Closes #827
  android/app/build.gradle
  ios/Lisk/Info.plist
  ios/LiskMessageExtension/Info.plist
  package-lock.json
  package.json
Labels: release

#833 Fix translation files - Closes #832
  locales/resources/de.json
  locales/resources/en.json
Labels: pending review

#842 Prevent rotation on Android - Closes #820
  android/app/src/main/AndroidManifest.xml
Labels: pending review

#843 Replace animations
  src/assets/animations/tx-confirmed.json
  src/assets/animations/tx-created.json
  src/assets/animations/tx-pending.json
  src/components/send/result/index.js
  src/components/send/result/styles.js
Labels: pending review

#838 Migrate home empty view to the new design - Closes #753
  locales/resources/de.json
  locales/resources/en.json
  src/assets/images/home/emptyHomeDark3x.png
  src/assets/images/home/emptyHomeLight3x.png
  src/assets/images/noActivity/noActivity3xDark.png
  src/assets/images/noActivity/noActivity3xLight.png
  src/components/accountSummary/home.js
  src/components/accountSummary/profile.js
  src/components/accountSummary/styles.js
  src/components/home/introModal/index.js
  src/components/router/headerBackground/index.js
  src/components/router/headerBackground/styles.js
  src/components/router/headerBackgroundImage/index.js
  src/components/router/headerBackgroundImage/styles.js
  src/components/router/homeHeaderTitle/styles.js
  src/components/router/index.js
  src/components/transactions/empty.js
  src/components/transactions/styles.js
  src/components/transactions/symbol.js
  src/constants/styleGuide/colors.js
Labels: pending review

#831 Migrate intro to new design - Closes #750
  locales/resources/de.json
  locales/resources/en.json
  src/assets/images/activityScreen.png
  src/assets/images/activityScreen2x.png
  src/assets/images/activityScreen3x.png
  src/assets/images/faceIdIllustration.png
  src/assets/images/faceIdIllustration2x.png
  src/assets/images/faceIdIllustration3x.png
  src/assets/images/frame.png
  src/assets/images/frame2x.png
  src/assets/images/frame3x.png
  src/assets/images/intro/activityHistory3x.png
  src/assets/images/intro/easyAccess3x.png
  src/assets/images/intro/secureAuthentication3x.png
  src/assets/images/intro/tokensTransfer3x.png
  src/assets/images/touchIdIllustration.png
  src/assets/images/touchIdIllustration2x.png
  src/assets/images/touchIdIllustration3x.png
  src/assets/images/transferScreen.png
  src/assets/images/transferScreen2x.png
  src/assets/images/transferScreen3x.png
  src/components/intro/heading.js
  src/components/intro/styles.js
Labels: pending review

#829 Quick action discreet mode
  src/components/signIn/index.js
  src/utilities/buildQuickActions.js
Labels: pending review
